version: '3'

volumes:
  product-node-modules:
  user-node-modules:
  order-node-modules:
  product-db-data:
  user-db-data:
  order-db-data:

networks:
  order-network:
    driver: bridge

services:
  frontend:
    

  product:
    

  product_db:
    image: mysql:5.7.22
    ports:
      

  user:
    

  user_db:
    image: mysql:5.7.22
    ports:
     


  order:
    

  order_db:
    image: mysql:5.7.22
    ports:
      

